name: kconmon
version: 0.0.0
description: A project for testing & monitor kubernetes nodes with TCP and UDP
keywords:
home:
sources:
  - https://github.com/Stono/kconmon
engine: gotpl
deprecated: false
