version: '3.2'
services:
  controller:
    image: barto92/kubemon:${VERSION:-latest}
    build:
      context: '.'
      args:
        NODEJS_VERSION: 14.4.0
    command: 'controller'
    environment:
      PORT: '80' # Run on port 80 locally in docker-compose to replicate kubernetes service object port magenting
    hostname: 'controller'
    domainname: 'kconmon.svc.cluster.local'
    networks:
      fake-kubernetes:
        aliases:
          - 'controller.kconmon.svc.cluster.local'
          - 'controller.kconmon'
          - 'controller'
    ports:
      - '8080:80'
    volumes:
      - ~/.config:/home/nonroot/.config:ro
      - ~/.kube:/home/nonroot/.kube:ro

  agent:
    image: barto92/kubemon:${VERSION:-latest}
    command: 'agent'
    environment:
      PORT: '80' # Run on port 80 locally in docker-compose to replicate kubernetes service object port magenting
    hostname: 'agent'
    domainname: 'kconmon.svc.cluster.local'
    networks:
      fake-kubernetes:
        aliases:
          - 'agent.kconmon.svc.cluster.local'
          - 'agent.kconmon'
          - 'agent'
    ports:
      - '8080:80'

networks:
  fake-kubernetes:
