name: Publish Docker Latest

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - helmfile/**
      - images/**
      - .vscode/**
      - samples/**

env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image
        run: docker-compose build

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u stono --password-stdin

      - name: Push image
        run: docker-compose push

  helm:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Package Helm
        run: |
          wget --quiet https://get.helm.sh/helm-v2.16.9-linux-amd64.tar.gz
          tar xf helm-v2.16.9-linux-amd64.tar.gz
          helm init --client-only
          cd ./helmfile/charts/kconmon
          ../../../linux-amd64/helm package .
          mv kconmon*.tgz kconmon-chart.tgz
