name: Publish Latest

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - helmfile/**
      - images/**
      - .vscode/**
      - samples/**

env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE: stono/kconmon
  VERSION: 0.0.0

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull image
        run: VERSION=latest docker-compose pull controller

      - name: Build image
        run: docker-compose build controller

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u stono --password-stdin

      - name: Push 0.0.0 image
        run: docker-compose push controller

      - name: Push latest image
        run: |
          docker tag $IMAGE:$VERSION $IMAGE:latest
          docker push $IMAGE:latest

  helm:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Package Helm
        run: |
          cd ./helmfile/charts/kconmon
          helm package --version=$VERSION .
          mv kconmon*.tgz kconmon-chart.tgz

      - name: Upload the helm chart
        uses: actions/upload-artifact@v1
        with:
          name: helm-chart
          path: ./helmfile/charts/kconmon/kconmon-chart.tgz
