name: Publish Docker Latest

on:
  push:
    branches:
      - master
    paths:
      - 'lib/**'
      - 'test/**'
      - 'Dockerfile'
      - 'docker-compose.yml'

env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image
        run: docker-compose build

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u stono --password-stdin

      - name: Push image
        run: docker-compose push
