name: Publish Docker Latest

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - helmfile/**
      - images/**
      - .vscode/**
      - samples/**

env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image
        run: docker-compose build

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u stono --password-stdin

      - name: Push image
        run: docker-compose push

  helm:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Package Helm
        run: |
          cd ./helmfile/charts/kconmon
          helm package .
          mv kconmon*.tgz kconmon-chart.tgz

      - name: Upload the helm file
        uses: actions/upload-artifact@v1
        with:
          name: helm-chart
          path: ./helmfile/charts/kconmon/kconmon-chart.tgz
